import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const netflixSans = localFont({
  src: [
    {
      path: "./fonts/NetflixSans-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/NetflixSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NetflixSans-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/NetflixSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Home - Netflix",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={netflixSans.className}>{children}</body>
    </html>
  );
}
